#!/bin/bash 

killPort=$1

if [[ ${killPort} == "" ]]; then
	echo -e "Please enter a port:"
	read killPort 
fi

if [[ ${killPort} != "" ]]; then
	if [[ $(lsof -i:${killPort}) ]]; then
		lsof -i:${killPort}
	else
		echo -e "There is no process running on that port. Exiting"
		exit;
	fi
else
	echo -e "You did not specify a port number. Exiting."
	exit;
fi	

echo -e "Kill process? [Y/n]"
read killAnswer 
killAnswer=$(echo ${killAnswer:0:1} | tr '[:lower:]' '[:upper:]')
if [[ ${killAnswer} == "Y" || ${killAnswer} == "" ]]; then
	kill $(lsof -t -i:${killPort})
	exit;
else
	exit;
fi
